from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from sqlalchemy import func, case
from datetime import datetime, timedelta, timezone
from database import get_db, engine
from models import Prediction
from schemas import StatsResponse, ModelInfoResponse
import json
import os

router = APIRouter(tags=["stats"])

# Path to the trained model info JSONs — generated by notebooks
_BASE_DIR        = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_MODEL_INFO_PATHS = {
    'kdd':    os.path.join(_BASE_DIR, 'models', 'model_info.json'),
    'cicids': os.path.join(_BASE_DIR, 'models', 'cicids_model_info.json'),
}

# ── In-memory cache for model info (avoids disk read on every request) ────────
_model_info_cache: dict = {}


def _model_info_path(model: str) -> str:
    return _MODEL_INFO_PATHS.get(model, _MODEL_INFO_PATHS['kdd'])


def _load_model_info(model: str) -> dict | None:
    """Load model_info.json from disk, with in-process caching."""
    if model in _model_info_cache:
        return _model_info_cache[model]
    info_path = _model_info_path(model)
    if not os.path.exists(info_path):
        return None
    try:
        with open(info_path, 'r') as f:
            data = json.load(f)
        _model_info_cache[model] = data
        return data
    except Exception:
        return None


def _accuracy_from_info(model: str) -> str:
    """Return accuracy string from model_info.json, or sensible fallback."""
    data = _load_model_info(model)
    if data and data.get('test_accuracy') is not None:
        return f"{data['test_accuracy'] * 100:.2f}%"
    # Per-model sensible defaults (not a single magic string)
    return '99.86%' if model == 'cicids' else '80.22%'


@router.get("/stats", response_model=StatsResponse)
def get_stats(
    model: str     = Query('kdd', description="Filter stats by model: 'kdd' or 'cicids'"),
    db:    Session = Depends(get_db),
):
    # Filter by model if specified
    q = db.query(Prediction)
    if model in ('kdd', 'cicids'):
        q = q.filter(Prediction.model_used == model)

    normal_label = 'Benign' if model == 'cicids' else 'Normal'

    total   = q.count()
    normal  = db.query(Prediction).filter(
        Prediction.model_used == model,
        Prediction.prediction == normal_label,
    ).count() if model in ('kdd', 'cicids') else db.query(Prediction).filter(Prediction.prediction == normal_label).count()
    attacks = total - normal

    # Distribution per category
    dist_q = db.query(
        Prediction.prediction,
        func.count(Prediction.id).label('count')
    )
    if model in ('kdd', 'cicids'):
        dist_q = dist_q.filter(Prediction.model_used == model)
    dist_raw = dist_q.group_by(Prediction.prediction).all()

    distribution = [{'name': r.prediction, 'value': r.count} for r in dist_raw]
    accuracy     = _accuracy_from_info(model)

    # Fall back to mock if no data yet
    if total == 0:
        if model == 'cicids':
            return StatsResponse(
                total=1979513, attacks=140200, normal=1839313,
                accuracy=accuracy,
                distribution=[
                    {'name': 'Benign',     'value': 1839313},
                    {'name': 'DoS',        'value': 87000  },
                    {'name': 'DDoS',       'value': 41835  },
                    {'name': 'PortScan',   'value': 10000  },
                    {'name': 'BruteForce', 'value': 1000   },
                    {'name': 'Bot',        'value': 365    },
                ]
            )
        return StatsResponse(
            total=125973, attacks=58630, normal=67343,
            accuracy=accuracy,
            distribution=[
                {'name': 'Normal', 'value': 67343},
                {'name': 'DoS',    'value': 45927},
                {'name': 'Probe',  'value': 11656},
                {'name': 'R2L',    'value': 995  },
                {'name': 'U2R',    'value': 52   },
            ]
        )

    return StatsResponse(
        total        = total,
        attacks      = attacks,
        normal       = normal,
        accuracy     = accuracy,
        distribution = distribution,
    )


@router.get("/model-info", response_model=ModelInfoResponse)
def get_model_info(
    model: str = Query('kdd', description="Model to query: 'kdd' or 'cicids'"),
):
    """
    Returns real model metadata from models/model_info.json or
    models/cicids_model_info.json depending on ?model= param.
    Falls back to static placeholder values if the file doesn't exist yet.
    Result is cached in memory after the first read.
    """
    data = _load_model_info(model)

    if data is not None:
        # The notebook stores confusion_matrix as dict-of-dicts:
        #   { "DoS": {"DoS": 6281, "Normal": 1126, ...}, ... }
        # Convert to the labels+matrix format the frontend table expects.
        classes = data.get('classes', list(data['confusion_matrix'].keys()))
        matrix  = [
            [data['confusion_matrix'][actual].get(pred, 0) for pred in classes]
            for actual in classes
        ]

        # feature_importance from notebook: [[name, score], ...]
        # Convert to [{"name": ..., "value": ...}] for Recharts BarChart
        fi_raw = data.get('feature_importance', [])
        if fi_raw and isinstance(fi_raw[0], list):
            feature_importance = [{'name': row[0], 'value': round(row[1], 6)}
                                   for row in fi_raw]
        else:
            feature_importance = fi_raw   # already correct shape

        return ModelInfoResponse(
            algorithm          = data.get('algorithm', 'XGBoost'),
            dataset            = data.get('dataset', 'NSL-KDD'),
            samples            = data.get('samples', 0),
            features           = data.get('features', 0),
            train_size         = data.get('train_size', ''),
            test_accuracy      = data.get('test_accuracy'),
            test_f1_weighted   = data.get('test_f1_weighted'),
            val_accuracy       = data.get('val_accuracy'),
            confusion_matrix   = {'labels': classes, 'matrix': matrix},
            feature_importance = feature_importance,
            classes            = classes,
            mlflow_run_id      = data.get('mlflow_run_id'),
            hyperparameters    = data.get('hyperparameters'),
        )

    # ── Fallback: notebook 03 hasn't been run yet ──────────────
    if model == 'cicids':
        return ModelInfoResponse(
            algorithm  = 'XGBoost',
            dataset    = 'CICIDS2017',
            samples    = 1979513,
            features   = 69,
            train_size = '80 / 20 split',
            confusion_matrix = {
                'labels': ['Benign', 'DoS', 'DDoS', 'PortScan', 'BruteForce', 'Bot', 'Infiltration'],
                'matrix': [
                    [1839313, 0, 0, 0, 0, 0, 0],
                    [0, 87000, 0, 0, 0, 0, 0],
                    [0, 0, 41835, 0, 0, 0, 0],
                    [0, 0, 0, 10000, 0, 0, 0],
                    [0, 0, 0, 0, 1000, 0, 0],
                    [0, 0, 0, 0, 0, 365, 0],
                    [0, 0, 0, 0, 0, 0, 5],
                ]
            },
            feature_importance = [
                {'name': 'Flow Duration',         'value': 0.14},
                {'name': 'Total Fwd Packets',     'value': 0.11},
                {'name': 'Fwd Packet Length Max', 'value': 0.09},
                {'name': 'Bwd Packet Length Max', 'value': 0.08},
                {'name': 'Flow Bytes/s',          'value': 0.07},
                {'name': 'Flow Packets/s',        'value': 0.07},
                {'name': 'Fwd IAT Total',         'value': 0.06},
                {'name': 'Bwd IAT Total',         'value': 0.05},
                {'name': 'Fwd Header Length',     'value': 0.05},
                {'name': 'Avg Fwd Segment Size',  'value': 0.04},
            ],
            classes = ['Benign', 'DoS', 'DDoS', 'PortScan', 'BruteForce', 'Bot', 'Infiltration'],
        )

    return ModelInfoResponse(
        algorithm  = 'XGBoost',
        dataset    = 'NSL-KDD',
        samples    = 125973,
        features   = 41,
        train_size = '80 / 20 split',
        confusion_matrix = {
            'labels': ['DoS', 'Normal', 'Probe', 'R2L', 'U2R'],
            'matrix': [
                [9180,    3,   0,   0,  0],
                [   2, 13420,   5,   1,  0],
                [   0,   10, 2320,  12,  0],
                [   0,   18,   5, 178,  0],
                [   0,    2,   0,   0,  8],
            ]
        },
        feature_importance = [
            {'name': 'serror_rate',          'value': 0.18},
            {'name': 'dst_host_serror_rate', 'value': 0.15},
            {'name': 'src_bytes',            'value': 0.12},
            {'name': 'srv_serror_rate',      'value': 0.10},
            {'name': 'count',                'value': 0.09},
            {'name': 'same_srv_rate',        'value': 0.08},
            {'name': 'dst_bytes',            'value': 0.07},
            {'name': 'logged_in',            'value': 0.06},
            {'name': 'dst_host_count',       'value': 0.05},
            {'name': 'flag',                 'value': 0.04},
        ]
    )


@router.get("/globe-stats")
def get_globe_stats(
    model: str     = Query('kdd', description="Filter by model: 'kdd' or 'cicids'"),
    db:    Session = Depends(get_db),
):
    """
    Returns attack counts grouped by source IP for the globe page.
    Only returns entries where src_ip was provided.
    """
    normal_labels = ['Normal', 'Benign']
    q = db.query(
        Prediction.src_ip,
        Prediction.prediction,
        func.count(Prediction.id).label('count')
    ).filter(
        Prediction.src_ip.isnot(None),
        Prediction.prediction.notin_(normal_labels),
    )
    if model in ('kdd', 'cicids'):
        q = q.filter(Prediction.model_used == model)

    results = q.group_by(
        Prediction.src_ip,
        Prediction.prediction
    ).order_by(
        func.count(Prediction.id).desc()
    ).limit(20).all()

    return [
        {'src_ip': r.src_ip, 'type': r.prediction, 'count': r.count}
        for r in results
    ]


@router.get("/stats/traffic")
def get_traffic(
    time_range: str = Query('24h', alias='range', description="Model filter: '6h', '12h', '24h', '7d'"),
    model:      str = Query('kdd', description="Model filter: 'kdd' or 'cicids'"),
    db:         Session = Depends(get_db),
):
    """
    Returns time-bucketed traffic counts for the Dashboard area chart.
    range: '6h' | '12h' | '24h' | '7d'
    Returns list of { t, n (normal), a (attacks) }

    Bucketing is done in SQL (not Python) to avoid loading all rows into memory.
    """
    now = datetime.now(timezone.utc)

    range_map = {
        '6h':  (timedelta(hours=6),  timedelta(hours=1),  6),
        '12h': (timedelta(hours=12), timedelta(hours=1),  12),
        '24h': (timedelta(hours=24), timedelta(hours=2),  12),
        '7d':  (timedelta(days=7),   timedelta(days=1),   7),
    }
    delta, bucket_size, num_buckets = range_map.get(time_range, range_map['24h'])
    since = now - delta

    normal_label = 'Benign' if model == 'cicids' else 'Normal'
    dialect_name = engine.dialect.name

    # ── Build SQL-level time bucket expression ─────────────────
    if dialect_name == 'postgresql':
        if time_range == '7d':
            bucket_expr = func.to_char(Prediction.created_at, 'Dy')
        else:
            bucket_expr = func.to_char(Prediction.created_at, 'HH24:00')
    else:
        # SQLite / other
        if time_range == '7d':
            bucket_expr = func.strftime('%w', Prediction.created_at)
        else:
            bucket_expr = func.strftime('%H:00', Prediction.created_at)

    q = db.query(
        bucket_expr.label('bucket'),
        func.sum(case((Prediction.prediction == normal_label, 1), else_=0)).label('n'),
        func.sum(case((Prediction.prediction != normal_label, 1), else_=0)).label('a'),
    ).filter(
        Prediction.created_at >= since
    )
    if model in ('kdd', 'cicids'):
        q = q.filter(Prediction.model_used == model)

    rows = q.group_by('bucket').order_by('bucket').all()

    if not rows:
        return []

    # Build label-keyed output with zero-fill for missing buckets
    result_map = {r.bucket: {'t': r.bucket, 'n': int(r.n), 'a': int(r.a)} for r in rows}

    # Generate expected bucket labels and fill missing ones with zeros
    buckets = []
    for i in range(num_buckets):
        bucket_start = since + i * bucket_size
        if time_range == '7d':
            label = bucket_start.strftime('%a')
        else:
            label = bucket_start.strftime('%H:00')
        entry = result_map.get(label, {'t': label, 'n': 0, 'a': 0})
        entry['t'] = label
        buckets.append(entry)

    return buckets
