from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import datetime, timedelta, timezone
from database import get_db
from models import Prediction
from schemas import StatsResponse, ModelInfoResponse
import json
import os

router = APIRouter(tags=["stats"])

# Path to the trained model info JSON — generated by notebook 03
_BASE_DIR       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_MODEL_INFO_PATH = os.path.join(_BASE_DIR, 'models', 'model_info.json')

@router.get("/stats", response_model=StatsResponse)
def get_stats(db: Session = Depends(get_db)):
    total   = db.query(Prediction).count()
    normal  = db.query(Prediction).filter(Prediction.prediction == 'Normal').count()
    attacks = total - normal

    # Distribution per category
    dist_raw = db.query(
        Prediction.prediction,
        func.count(Prediction.id).label('count')
    ).group_by(Prediction.prediction).all()

    distribution = [{'name': r.prediction, 'value': r.count} for r in dist_raw]

    # Fall back to mock if no data yet
    if total == 0:
        return StatsResponse(
            total=125973, attacks=58630, normal=67343,
            accuracy='97.4%',
            distribution=[
                {'name': 'Normal', 'value': 67343},
                {'name': 'DoS',    'value': 45927},
                {'name': 'Probe',  'value': 11656},
                {'name': 'R2L',    'value': 995  },
                {'name': 'U2R',    'value': 52   },
            ]
        )

    return StatsResponse(
        total        = total,
        attacks      = attacks,
        normal       = normal,
        accuracy     = '97.4%',
        distribution = distribution,
    )


@router.get("/model-info", response_model=ModelInfoResponse)
def get_model_info():
    """
    Returns real model metadata from models/model_info.json (written by
    notebook 03_model_training.ipynb).  Falls back to static placeholder
    values if the file doesn't exist yet.
    """
    if os.path.exists(_MODEL_INFO_PATH):
        with open(_MODEL_INFO_PATH, 'r') as f:
            data = json.load(f)

        # The notebook stores confusion_matrix as dict-of-dicts:
        #   { "DoS": {"DoS": 6281, "Normal": 1126, ...}, ... }
        # Convert to the labels+matrix format the frontend table expects.
        classes = data.get('classes', list(data['confusion_matrix'].keys()))
        matrix  = [
            [data['confusion_matrix'][actual].get(pred, 0) for pred in classes]
            for actual in classes
        ]

        # feature_importance from notebook: [[name, score], ...]
        # Convert to [{"name": ..., "value": ...}] for Recharts BarChart
        fi_raw = data.get('feature_importance', [])
        if fi_raw and isinstance(fi_raw[0], list):
            feature_importance = [{'name': row[0], 'value': round(row[1], 6)}
                                   for row in fi_raw]
        else:
            feature_importance = fi_raw   # already correct shape

        return ModelInfoResponse(
            algorithm          = data.get('algorithm', 'XGBoost'),
            dataset            = data.get('dataset', 'NSL-KDD'),
            samples            = data.get('samples', 0),
            features           = data.get('features', 0),
            train_size         = data.get('train_size', ''),
            test_accuracy      = data.get('test_accuracy'),
            test_f1_weighted   = data.get('test_f1_weighted'),
            val_accuracy       = data.get('val_accuracy'),
            confusion_matrix   = {'labels': classes, 'matrix': matrix},
            feature_importance = feature_importance,
            classes            = classes,
            mlflow_run_id      = data.get('mlflow_run_id'),
            hyperparameters    = data.get('hyperparameters'),
        )

    # ── Fallback: notebook 03 hasn't been run yet ──────────────
    return ModelInfoResponse(
        algorithm  = 'XGBoost',
        dataset    = 'NSL-KDD',
        samples    = 125973,
        features   = 41,
        train_size = '80 / 20 split',
        confusion_matrix = {
            'labels': ['DoS', 'Normal', 'Probe', 'R2L', 'U2R'],
            'matrix': [
                [9180,    3,   0,   0,  0],
                [   2, 13420,   5,   1,  0],
                [   0,   10, 2320,  12,  0],
                [   0,   18,   5, 178,  0],
                [   0,    2,   0,   0,  8],
            ]
        },
        feature_importance = [
            {'name': 'serror_rate',          'value': 0.18},
            {'name': 'dst_host_serror_rate', 'value': 0.15},
            {'name': 'src_bytes',            'value': 0.12},
            {'name': 'srv_serror_rate',      'value': 0.10},
            {'name': 'count',                'value': 0.09},
            {'name': 'same_srv_rate',        'value': 0.08},
            {'name': 'dst_bytes',            'value': 0.07},
            {'name': 'logged_in',            'value': 0.06},
            {'name': 'dst_host_count',       'value': 0.05},
            {'name': 'flag',                 'value': 0.04},
        ]
    )


@router.get("/globe-stats")
def get_globe_stats(db: Session = Depends(get_db)):
    """
    Returns attack counts grouped by source IP for the globe page.
    Only returns entries where src_ip was provided.
    """
    results = db.query(
        Prediction.src_ip,
        Prediction.prediction,
        func.count(Prediction.id).label('count')
    ).filter(
        Prediction.src_ip.isnot(None),
        Prediction.prediction != 'Normal'
    ).group_by(
        Prediction.src_ip,
        Prediction.prediction
    ).order_by(
        func.count(Prediction.id).desc()
    ).limit(20).all()

    return [
        {'src_ip': r.src_ip, 'type': r.prediction, 'count': r.count}
        for r in results
    ]


@router.get("/stats/traffic")
def get_traffic(
    range: str = '24h',
    db: Session = Depends(get_db),
):
    """
    Returns time-bucketed traffic counts for the Dashboard area chart.
    range: '6h' | '12h' | '24h' | '7d'
    Returns list of { t, n (normal), a (attacks) }
    """
    now = datetime.now(timezone.utc)

    range_map = {
        '6h':  (timedelta(hours=6),   timedelta(hours=1),   '%H:00'),
        '12h': (timedelta(hours=12),  timedelta(hours=1),   '%H:00'),
        '24h': (timedelta(hours=24),  timedelta(hours=2),   '%H:00'),
        '7d':  (timedelta(days=7),    timedelta(days=1),    '%a'),
    }
    delta, bucket_size, fmt = range_map.get(range, range_map['24h'])
    since = now - delta

    rows = db.query(Prediction).filter(
        Prediction.created_at >= since
    ).all()

    # Build buckets
    num_buckets = int(delta / bucket_size)
    buckets = []
    for i in range(num_buckets):
        bucket_start = since + i * bucket_size
        bucket_end   = bucket_start + bucket_size
        label = bucket_start.strftime(fmt)
        normal  = sum(1 for r in rows if bucket_start <= r.created_at.replace(tzinfo=timezone.utc) < bucket_end and r.prediction == 'Normal')
        attacks = sum(1 for r in rows if bucket_start <= r.created_at.replace(tzinfo=timezone.utc) < bucket_end and r.prediction != 'Normal')
        buckets.append({'t': label, 'n': normal, 'a': attacks})

    # If no DB data at all, return empty list — frontend falls back to mock
    if not rows:
        return []

    return buckets
